---
- name: Check if restart is required.
  postgresql_query:
    db: postgres
    query: SELECT name from pg_settings where pending_restart = true;
  become_user: postgres
  become: true
  register: pending_restart

- name: Notify if restart required.
  debug:
    msg: "ATTENTION: Restart required for {{ pending_restart.query_result }}!"
  when: pending_restart.rowcount > 0
