---
- name: Install PostgreSQL packages
  yum:
    state: present
    name:
      - "postgresql{{ postgresql_version | replace('.', '') }}"
      - "postgresql{{ postgresql_version | replace('.', '') }}-server"
      - "postgresql{{ postgresql_version | replace('.', '') }}-contrib"
      - "postgresql{{ postgresql_version | replace('.', '') }}-libs"
      - python3-psycopg2
      - python-psycopg2
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - powa_{{ postgresql_version | replace('.', '') }}
      - pg_qualstats{{ postgresql_version | replace('.', '') }}
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - hypopg_{{ postgresql_version | replace('.', '') }}
      - repmgr{{ postgresql_version | replace('.', '') }}

- name: Install support packages for partoni
  yum:
    state: present
    name:
      - gcc
      - python3-devel
      - python3-pip
      - python-setuptools
      - python3-setuptools
  when: postgresql_service == "patroni"

- name: Install Patroni with etcd
  pip:
    name:
      - "patroni[etcd]"
    state: present
    executable: pip3
  when: etcd_hosts is defined and postgresql_service == "patroni"

- name: Install Patroni with consul
  pip:
    name:
      - "patroni[consul]"
    state: present
    executable: pip3
  when: consul_host is defined and postgresql_service == "patroni"
