---
- name: "Install PostgreSQL packages."
  yum: 
    state: latest
    name:
      - "postgresql{{ postgresql_version | replace('.', '') }}"
      - "postgresql{{ postgresql_version | replace('.', '') }}-server"
      - "postgresql{{ postgresql_version | replace('.', '') }}-contrib"
      - "postgresql{{ postgresql_version | replace('.', '') }}-libs"
      # is devel really needed?
      #- "postgresql{{ postgresql_version | replace('.', '') }}-devel"
      - python-psycopg2
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - powa_{{ postgresql_version | replace('.', '') }}
      - pg_qualstats{{ postgresql_version | replace('.', '') }}
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - hypopg_{{ postgresql_version | replace('.', '') }}
      - powa_{{ postgresql_version | replace('.', '') }}-web
      - repmgr{{ postgresql_version | replace('.', '') }}
