---
- name: Disable the built-in PostgreSQL module on Centos 8
  # Find a way to do in without command!
  command: dnf -qy module disable postgresql
  register: result
  when: ansible_distribution_major_version|int == 8
  changed_when: '"Nothing to do" in result.stdout'

- name: Install python-psycopg2 for Centos7
  package:
    state: present
    name:
      - python-psycopg2
  when: ansible_distribution_major_version|int == 7

- name: Install PostgreSQL packages
  package:
    state: present
    name:
      - "postgresql{{ postgresql_version | replace('.', '') }}"
      - "postgresql{{ postgresql_version | replace('.', '') }}-server"
      - "postgresql{{ postgresql_version | replace('.', '') }}-contrib"
      - "postgresql{{ postgresql_version | replace('.', '') }}-libs"
      - python3-psycopg2
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - powa_{{ postgresql_version | replace('.', '') }}
      - pg_qualstats{{ postgresql_version | replace('.', '') }}
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - hypopg_{{ postgresql_version | replace('.', '') }}
      - repmgr{{ postgresql_version | replace('.', '') }}
      - pg_wait_sampling_{{ postgresql_version | replace('.', '') }}

- name: Install support packages for partoni
  yum:
    state: present
    name:
      - gcc
      - python3-devel
      - python3-pip
      - python3-setuptools
  when: postgresql_service == "patroni"

- name: Install python-setuptools for Centos7
  package:
    state: present
    name:
      - python-setuptools
  when: ansible_distribution_major_version|int == 7 and postgresql_service == "patroni"

- name: Install Patroni with etcd
  pip:
    name:
      - "patroni[etcd]"
    state: present
    executable: pip3
  when: etcd_hosts is defined and postgresql_service == "patroni"

- name: Install Patroni with consul
  pip:
    name:
      - "patroni[consul]"
    state: present
    executable: pip3
  when: consul_host is defined and postgresql_service == "patroni"
