---
- name: Create /etc/patroni
  file:
    state: directory
    dest: /etc/patroni

- name: Create patroni systemd service
  template:
    src: patroni.service.j2
    dest: "/etc/systemd/system/patroni.service"
    owner: root
    group: root
    backup: true
    force: true
    mode: 0644

- name: Create patroni config file from template
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    backup: true
  notify:
    - reload patroni

- name: Start and enable patroni
  systemd:
    name: patroni
    state: started
    enabled: true
    daemon_reload: true

- name: Check patroni api responce
  # This task is essential to determine current master
  # and run powa tasks on him instead of entire cluster
  uri:
    url: http://localhost:8008
    body_format: json
    status_code: [200, 503]
  register: output

- name: Cluster check results
  debug:
    msg: "role: {{ output.json.role }} state: {{ output.json.state }}"

- name: Check if restart pending
  debug:
    msg: "pending_restart: {{ output.json.pending_restart }}"
  when: "'pending_restart' in output.json"
