---
- name: Install pgbadger and httpd.
  yum:
    state: latest
    name:
      - pgbadger
      - httpd
  tags: slave

- name: Add firewall exception for http. Ignore if firewall is off.
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  tags: slave
    
- name: Setup postgresql for extended logging.
  template: 
      src: 30postgresql_logging.conf.j2
      dest: "{{ pg_conf }}/conf.d/30postgresql_logging.conf"
      owner: "{{ postgresql_admin_user }}"
      group: "{{ postgresql_admin_user }}"
      backup: yes
  notify: reload postgres  
    
- name: Start and enable httpd service.
  service:
    name: httpd
    state: started
    enabled: yes
  tags: slave

- name: Create apache badger directory.
  file:
    path: /var/www/badger
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    state: directory
    mode: 0755
  tags: slave

- name: Place config for badger site.
  template:
    src: http.conf
    dest: /etc/httpd/conf.d/badger.conf
  notify: restart httpd
  tags: slave 

- name: Put badger script for hourly cron.
  template:
    src: badger_cron_hourly.j2
    dest: ~/badger_cron_hourly.sh
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0700
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  tags: slave

- name: Configure cron for badger.
  cron:
    name: "pgbadber daily"
    user: "{{ postgresql_admin_user }}"
    minute: "50"
    hour: "23"
    job: "~/badger_cron_daily.sh &>/tmp/pgbadger.log"
  tags: slave
