---
- name: Create POWA database.
  postgresql_db:
    name: powa
    state: present
    port: "{{ postgresql_port }}"
  become_user: postgres

- name: Create extensions.
  postgresql_ext:
    name: "{{ item[1] }}"
    db: "{{ item[0] }}"
    port: "{{ postgresql_port }}"
  become_user: postgres
  with_nested:
    - [ postgres, powa ]
    - [ pg_stat_statements, btree_gist, powa, pg_qualstats, pg_stat_kcache, pg_buffercache ]

- name: Get databases list.
  command: psql -p "{{ postgresql_port }}" -t -c "select datname from pg_database where datname <> 'template0';"
  become: true
  become_user: postgres
  register: database_list
  check_mode: no

- name: Create extension powa in databases.
  postgresql_ext:
    name: hypopg 
    db: "{{ item[0] }}"
    port: "{{ postgresql_port }}"
  become_user: postgres
  with_nested: "{{ database_list.stdout_lines }}"

- name: Create POWA user.
  postgresql_user:
    name: powa
    role_attr_flags: SUPERUSER
    port: "{{ postgresql_port }}"
  become_user: postgres

#- name: Set powa-web config.
#  template: 
#      src: powa-web.conf.j2
#      dest: "/etc/powa-web.conf"
#      owner: "{{ postgresql_admin_user }}"
#      group: "{{ postgresql_admin_user }}"
#      backup: yes
#  tags: slave
