---
- name: Create REPMGR user.
  postgresql_user:
    name: repmgr
    password:
    role_attr_flags: SUPERUSER,REPLICATION
    port: "{{ postgresql_port }}"
  become_user: postgres

- name: Create REPMGR database.
  postgresql_db:
    name: repmgr
    state: present
    owner: repmgr
    port: "{{ postgresql_port }}"
  become_user: postgres

- name: Create extensions.
  postgresql_ext:
    name: repmgr
    db: repmgr
    port: "{{ postgresql_port }}"
  become_user: postgres
