---
- name: "prepare. install etcd"
  hosts: etcd
  vars:
    ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://{{ ansible_hostname }}:2380"
    ETCD_ADVERTISE_CLIENT_URLS: "http://{{ ansible_hostname }}:2379"
    ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
    ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380"
  roles:
    - role: proxy_settings
    - role: etcd  

- name: "prepare. install postgres"
  hosts: postgres
  vars:
    etcd_hosts: "etcd1:2379"
    postgresql_service: patroni
    postgresql_version: 11
    postgresql_hba:
      - local all all peer
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust
      - local replication all trust
      - host replication all 0.0.0.0/0 trust
      - host replication all 127.0.0.1/32 trust
      - host replication all ::1/128 trust
  roles:
    - role: epel
    - role: postgresql