---
- name: Converge
  hosts: postgres
  vars:
    etcd_hosts: "etcd1:2379,etcd2:2379,etcd3:2379"
    postgresql_service: patroni
    postgresql_hba:
      - local all all peer
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust
      - local replication all trust
      - host replication all 0.0.0.0/0 trust
      - host replication all 127.0.0.1/32 trust
      - host replication all ::1/128 trust
  roles:
    - role: postgresql
