---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: patroni1
    image: centos:7
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      no_proxy: "${no_proxy},patroni1,patroni2,patroni3"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: patroninet
  - name: patroni2
    image: centos:7
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      no_proxy: "${no_proxy},patroni1,patroni2,patroni3"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: patroninet
  - name: patroni3
    image: centos:7
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${http_proxy}"
      no_proxy: "${no_proxy},patroni1,patroni2,patroni3"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: patroninet
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
